services:
  server:
    container_name: assettoserverdocker
    build: .
    #image: assettoserverdocker
    ports:
      - "9600:9600"
      - "9600:9600/udp"
      - "8081:8081"
    volumes:
      - ./data:/data